name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v6

    - name: "Setup Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"

    - name: "Install Dependencies"
      shell: bash
      run: |
        set -eo pipefail
        gem install kramdown-rfc cddlc cddl edn-abnf
        pip install xml2rfc cbor2

    - name: "Validate CDDL and CBOR Examples from Draft XML"
      shell: bash
      run: |
        set -eo pipefail

        make draft-ietf-scitt-receipts-ccf-profile.xml
        ./samples/validate-cbor-examples.sh draft-ietf-scitt-receipts-ccf-profile.xml

    - name: "Setup"
      id: setup
      run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"

    - name: "Caching"
      uses: actions/cache@v5
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      if: ${{ github.event_name == 'push' }}
      with:
        make: gh-pages
        token: ${{ github.token }}

    - name: "Archive Built Drafts"
      uses: actions/upload-artifact@v7
      with:
        path: |
          draft-*.html
          draft-*.txt
